"""
Sensitivity analysis: ARI vs n_neighbors on a 100k-point dataset.

Sweeps n_neighbors over a grid spanning [10, 500] and records:
  - ARI vs ground truth
  - clusters discovered
  - effective sigma (auto-derived)
  - end-to-end runtime
  - peak RSS in MB

Emits CSV at results/sensitivity_n_neighbors.csv and a LaTeX-ready
table at paper/sensitivity_table.tex.
"""
from __future__ import annotations

import os, resource, sys, time, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.metrics import adjusted_rand_score, normalized_mutual_info_score
from sklearn.preprocessing import StandardScaler

from trcc import TRCC


def rss_mb():
    # macOS reports ru_maxrss in bytes; Linux reports kilobytes
    raw = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
    return raw / (1024 * 1024) if sys.platform == "darwin" else raw / 1024


def main(n=100_000, centers=12, std=0.6, seed=0):
    print(f"Generating make_blobs(n={n}, centers={centers}, std={std})")
    X, y = make_blobs(n_samples=n, centers=centers, cluster_std=std,
                      random_state=seed)
    X = StandardScaler().fit_transform(X)
    print(f"X shape={X.shape}\n")

    # Range from the user's spec: 10..500 with denser sampling at lower end
    grid = [10, 15, 20, 30, 40, 50, 75, 100, 125, 150, 175, 200, 250, 300, 400, 500]

    rows = []
    print(f"{'n_nbrs':>7s} {'k_found':>8s} {'ARI':>7s} {'NMI':>7s} {'time_s':>8s} {'RSS_MB':>8s}")
    print("-" * 55)
    for nn in grid:
        t0 = time.perf_counter()
        m = TRCC(n_neighbors=nn).fit(X)
        dt = time.perf_counter() - t0
        valid = m.labels_ != -1
        k_found = int(len(np.unique(m.labels_[valid]))) if valid.any() else 0
        ari = float(adjusted_rand_score(y, m.labels_))
        nmi = float(normalized_mutual_info_score(y, m.labels_))
        rss = rss_mb()
        rows.append({
            "n_neighbors": nn, "k_found": k_found, "ARI": ari, "NMI": nmi,
            "runtime_s": dt, "rss_mb": rss,
        })
        print(f"{nn:>7d} {k_found:>8d} {ari:>7.3f} {nmi:>7.3f} {dt:>8.2f} {rss:>8.0f}")

    # Default formula: clip(ceil(sqrt(n)/2), 10, 200)
    n_eff = int(np.clip(np.ceil(np.sqrt(n) / 2.0), 10, 200))
    print(f"\nDefault auto value at n={n}: n_neighbors = {n_eff}  "
          f"(formula: clip(ceil(sqrt(n)/2), 10, 200))")

    df = pd.DataFrame(rows)
    out_csv = "results/sensitivity_n_neighbors.csv"
    df.to_csv(out_csv, index=False)
    print(f"\nWrote {out_csv}")

    # LaTeX table
    latex = [
        r"% Auto-generated by scripts/sensitivity_n_neighbors.py",
        r"% Dataset: make_blobs(n=" + str(n) + r", centers=" + str(centers) +
        r", std=" + str(std) + r")",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Sensitivity of TRCC v1.1 to the \textit{n\_neighbors} hyperparameter "
        r"on a $" + f"{n:,}".replace(",", r"\,") + r"$-point dataset with "
        + str(centers) + r" Gaussian clusters. The default heuristic "
        r"$k_{nn}(n) = \min(200, \max(10, \lceil\sqrt{n}/2\rceil)) = " + str(n_eff)
        + r"$ is highlighted.}",
        r"\label{tab:sensitivity_kn}",
        r"\begin{tabular}{rrrrrr}",
        r"\toprule",
        r"$n_{\text{nbrs}}$ & $\hat{k}$ & ARI & NMI & runtime (s) & RSS (MB) \\",
        r"\midrule",
    ]
    for _, r in df.iterrows():
        nn = int(r["n_neighbors"])
        bold = (nn == n_eff)
        fmt = (r"\textbf{%d} & \textbf{%d} & \textbf{%.3f} & \textbf{%.3f} & \textbf{%.2f} & \textbf{%.0f}"
               if bold else r"%d & %d & %.3f & %.3f & %.2f & %.0f")
        latex.append(fmt % (nn, int(r['k_found']), r['ARI'], r['NMI'],
                            r['runtime_s'], r['rss_mb']) + r" \\")
    latex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    out_tex = "paper/sensitivity_table.tex"
    os.makedirs("paper", exist_ok=True)
    with open(out_tex, "w") as f:
        f.write("\n".join(latex))
    print(f"Wrote {out_tex}")


if __name__ == "__main__":
    main()
